[package]
name = "alertaemcena"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
reqwest = "0.12"
scraper = "0.19"
tokio = { version = "1", features = ["full"] }
openssl = { version = "0.10", features = ["vendored"] }
futures = "0.3.30"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4.38"
itertools = "0.13"
